const Router = require('express')
const router = new Router()
const productRouter = require('./productRouter')
const categoryRouter = require('./categoryRouter')
const manufacturerRouter = require('./manufacturerRouter')
const cartRouter = require('./cartRouter')
const reviewRouter = require('./reviewRouter')
const userRouter = require('./userRouter')
const orderRouter = require('./orderRouter')
const orderStatus = require('./orderStatusRouter')
const reviewStatus = require('./reviewStatusRouter')

router.use('/category', categoryRouter)
router.use('/product', productRouter)
router.use('/manufacturer', manufacturerRouter)
router.use('/user' , userRouter)
router.use('/cart' , cartRouter)
router.use('/review', reviewRouter)
router.use('/order', orderRouter)
router.use('/orderStatus', orderStatus)
router.use('/reviewStatus', reviewStatus)

module.exports = router
